# https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd
# https://github.com/containerd/containerd/blob/main/docs/getting-started.md
# https://docs.docker.com/engine/install/debian/#install-using-the-repository

---

  - name: Gathering facts about /etc/apt/keyrings/docker.key existence
    ansible.builtin.stat:
      path: /etc/apt/keyrings/docker.key
    register: register_name

  - name: Download the public signing key for the Docker package repositories
    ansible.builtin.get_url:
      url: https://download.docker.com/linux/debian/gpg
      dest: /root/docker.gpg
    when: not register_name.stat.exists

  - name: Add the signing key for the Docker package repositories to the apt keyring
    ansible.builtin.shell: cat /root/docker.gpg | gpg --dearmor -o /etc/apt/keyrings/docker.key
    when: not register_name.stat.exists

  - name: Add the Docker apt repository to apt sources
    ansible.builtin.lineinfile:
      path: /etc/apt/sources.list.d/docker.list
      line: deb [signed-by=/etc/apt/keyrings/docker.key] https://download.docker.com/linux/debian   bookworm stable
      create: yes

  - name: Install Docker (containerd) packages
    ansible.builtin.apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin



