# https://kubernetes.io/docs/setup/production-environment/container-runtimes/#forwarding-ipv4-and-letting-iptables-see-bridged-traffic

---

    - name: Add modules to /etc/modules-load.d/k8s.conf
      become: yes
      ansible.builtin.blockinfile:
        path: /etc/modules-load.d/k8s.conf
        block: |
          overlay
          br_netfilter
        create: yes

    - name: Insert module overlay
      become: yes
      community.general.modprobe:
        name: overlay
        state: present
        persistent: present

    - name: Insert module br_netfilter
      become: yes
      community.general.modprobe:
        name: br_netfilter
        state: present
        persistent: present

    - name: Add sysctl params in /etc/sysctl.d/k8s.conf
      become: yes
      ansible.builtin.blockinfile:
        path: /etc/sysctl.d/k8s.conf
        block: |
          net.bridge.bridge-nf-call-iptables=1
          net.bridge.bridge-nf-call-ip6tables=1
          net.ipv4.ip_forward=1
        create: yes

    - name: Apply sysctl params without reboot
      become: yes
      ansible.builtin.command: sysctl --system
