---
# This task will install common packages for Debian

  - name: 'Install common packages for Debian'
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - apt-transport-https
      - curl
      - gnupg-agent
      - software-properties-common
